# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dymk/code/c/all_the_tags

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dymk/code/c/all_the_tags

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"bin\" \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.4.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dymk/code/c/all_the_tags/CMakeFiles /Users/dymk/code/c/all_the_tags/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dymk/code/c/all_the_tags/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named all_the_tags

# Build rule for target.
all_the_tags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_the_tags
.PHONY : all_the_tags

# fast build rule for target.
all_the_tags/fast:
	$(MAKE) -f CMakeFiles/all_the_tags.dir/build.make CMakeFiles/all_the_tags.dir/build
.PHONY : all_the_tags/fast

#=============================================================================
# Target rules for targets named all_the_tags_testrunner

# Build rule for target.
all_the_tags_testrunner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_the_tags_testrunner
.PHONY : all_the_tags_testrunner

# fast build rule for target.
all_the_tags_testrunner/fast:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/build
.PHONY : all_the_tags_testrunner/fast

#=============================================================================
# Target rules for targets named asmjit

# Build rule for target.
asmjit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asmjit
.PHONY : asmjit

# fast build rule for target.
asmjit/fast:
	$(MAKE) -f asmjit/CMakeFiles/asmjit.dir/build.make asmjit/CMakeFiles/asmjit.dir/build
.PHONY : asmjit/fast

#=============================================================================
# Target rules for targets named hayai_main

# Build rule for target.
hayai_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hayai_main
.PHONY : hayai_main

# fast build rule for target.
hayai_main/fast:
	$(MAKE) -f test/hayai/src/CMakeFiles/hayai_main.dir/build.make test/hayai/src/CMakeFiles/hayai_main.dir/build
.PHONY : hayai_main/fast

#=============================================================================
# Target rules for targets named sample

# Build rule for target.
sample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample
.PHONY : sample

# fast build rule for target.
sample/fast:
	$(MAKE) -f test/hayai/sample/CMakeFiles/sample.dir/build.make test/hayai/sample/CMakeFiles/sample.dir/build
.PHONY : sample/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f test/hayai/vendor/gtest/CMakeFiles/gtest.dir/build.make test/hayai/vendor/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f test/hayai/vendor/gtest/CMakeFiles/gtest_main.dir/build.make test/hayai/vendor/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f test/hayai/tests/CMakeFiles/tests.dir/build.make test/hayai/tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

context.o: context.cc.o

.PHONY : context.o

# target to build an object file
context.cc.o:
	$(MAKE) -f CMakeFiles/all_the_tags.dir/build.make CMakeFiles/all_the_tags.dir/context.cc.o
.PHONY : context.cc.o

context.i: context.cc.i

.PHONY : context.i

# target to preprocess a source file
context.cc.i:
	$(MAKE) -f CMakeFiles/all_the_tags.dir/build.make CMakeFiles/all_the_tags.dir/context.cc.i
.PHONY : context.cc.i

context.s: context.cc.s

.PHONY : context.s

# target to generate assembly for a file
context.cc.s:
	$(MAKE) -f CMakeFiles/all_the_tags.dir/build.make CMakeFiles/all_the_tags.dir/context.cc.s
.PHONY : context.cc.s

query.o: query.cc.o

.PHONY : query.o

# target to build an object file
query.cc.o:
	$(MAKE) -f CMakeFiles/all_the_tags.dir/build.make CMakeFiles/all_the_tags.dir/query.cc.o
.PHONY : query.cc.o

query.i: query.cc.i

.PHONY : query.i

# target to preprocess a source file
query.cc.i:
	$(MAKE) -f CMakeFiles/all_the_tags.dir/build.make CMakeFiles/all_the_tags.dir/query.cc.i
.PHONY : query.cc.i

query.s: query.cc.s

.PHONY : query.s

# target to generate assembly for a file
query.cc.s:
	$(MAKE) -f CMakeFiles/all_the_tags.dir/build.make CMakeFiles/all_the_tags.dir/query.cc.s
.PHONY : query.cc.s

tag.o: tag.cc.o

.PHONY : tag.o

# target to build an object file
tag.cc.o:
	$(MAKE) -f CMakeFiles/all_the_tags.dir/build.make CMakeFiles/all_the_tags.dir/tag.cc.o
.PHONY : tag.cc.o

tag.i: tag.cc.i

.PHONY : tag.i

# target to preprocess a source file
tag.cc.i:
	$(MAKE) -f CMakeFiles/all_the_tags.dir/build.make CMakeFiles/all_the_tags.dir/tag.cc.i
.PHONY : tag.cc.i

tag.s: tag.cc.s

.PHONY : tag.s

# target to generate assembly for a file
tag.cc.s:
	$(MAKE) -f CMakeFiles/all_the_tags.dir/build.make CMakeFiles/all_the_tags.dir/tag.cc.s
.PHONY : tag.cc.s

test/bench_query.o: test/bench_query.cc.o

.PHONY : test/bench_query.o

# target to build an object file
test/bench_query.cc.o:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/bench_query.cc.o
.PHONY : test/bench_query.cc.o

test/bench_query.i: test/bench_query.cc.i

.PHONY : test/bench_query.i

# target to preprocess a source file
test/bench_query.cc.i:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/bench_query.cc.i
.PHONY : test/bench_query.cc.i

test/bench_query.s: test/bench_query.cc.s

.PHONY : test/bench_query.s

# target to generate assembly for a file
test/bench_query.cc.s:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/bench_query.cc.s
.PHONY : test/bench_query.cc.s

test/runner.o: test/runner.cc.o

.PHONY : test/runner.o

# target to build an object file
test/runner.cc.o:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/runner.cc.o
.PHONY : test/runner.cc.o

test/runner.i: test/runner.cc.i

.PHONY : test/runner.i

# target to preprocess a source file
test/runner.cc.i:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/runner.cc.i
.PHONY : test/runner.cc.i

test/runner.s: test/runner.cc.s

.PHONY : test/runner.s

# target to generate assembly for a file
test/runner.cc.s:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/runner.cc.s
.PHONY : test/runner.cc.s

test/test_entitity_tagging.o: test/test_entitity_tagging.cc.o

.PHONY : test/test_entitity_tagging.o

# target to build an object file
test/test_entitity_tagging.cc.o:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_entitity_tagging.cc.o
.PHONY : test/test_entitity_tagging.cc.o

test/test_entitity_tagging.i: test/test_entitity_tagging.cc.i

.PHONY : test/test_entitity_tagging.i

# target to preprocess a source file
test/test_entitity_tagging.cc.i:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_entitity_tagging.cc.i
.PHONY : test/test_entitity_tagging.cc.i

test/test_entitity_tagging.s: test/test_entitity_tagging.cc.s

.PHONY : test/test_entitity_tagging.s

# target to generate assembly for a file
test/test_entitity_tagging.cc.s:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_entitity_tagging.cc.s
.PHONY : test/test_entitity_tagging.cc.s

test/test_helper.o: test/test_helper.cc.o

.PHONY : test/test_helper.o

# target to build an object file
test/test_helper.cc.o:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_helper.cc.o
.PHONY : test/test_helper.cc.o

test/test_helper.i: test/test_helper.cc.i

.PHONY : test/test_helper.i

# target to preprocess a source file
test/test_helper.cc.i:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_helper.cc.i
.PHONY : test/test_helper.cc.i

test/test_helper.s: test/test_helper.cc.s

.PHONY : test/test_helper.s

# target to generate assembly for a file
test/test_helper.cc.s:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_helper.cc.s
.PHONY : test/test_helper.cc.s

test/test_query.o: test/test_query.cc.o

.PHONY : test/test_query.o

# target to build an object file
test/test_query.cc.o:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_query.cc.o
.PHONY : test/test_query.cc.o

test/test_query.i: test/test_query.cc.i

.PHONY : test/test_query.i

# target to preprocess a source file
test/test_query.cc.i:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_query.cc.i
.PHONY : test/test_query.cc.i

test/test_query.s: test/test_query.cc.s

.PHONY : test/test_query.s

# target to generate assembly for a file
test/test_query.cc.s:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_query.cc.s
.PHONY : test/test_query.cc.s

test/test_tag_implication.o: test/test_tag_implication.cc.o

.PHONY : test/test_tag_implication.o

# target to build an object file
test/test_tag_implication.cc.o:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_tag_implication.cc.o
.PHONY : test/test_tag_implication.cc.o

test/test_tag_implication.i: test/test_tag_implication.cc.i

.PHONY : test/test_tag_implication.i

# target to preprocess a source file
test/test_tag_implication.cc.i:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_tag_implication.cc.i
.PHONY : test/test_tag_implication.cc.i

test/test_tag_implication.s: test/test_tag_implication.cc.s

.PHONY : test/test_tag_implication.s

# target to generate assembly for a file
test/test_tag_implication.cc.s:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_tag_implication.cc.s
.PHONY : test/test_tag_implication.cc.s

test/test_tag_values.o: test/test_tag_values.cc.o

.PHONY : test/test_tag_values.o

# target to build an object file
test/test_tag_values.cc.o:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_tag_values.cc.o
.PHONY : test/test_tag_values.cc.o

test/test_tag_values.i: test/test_tag_values.cc.i

.PHONY : test/test_tag_values.i

# target to preprocess a source file
test/test_tag_values.cc.i:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_tag_values.cc.i
.PHONY : test/test_tag_values.cc.i

test/test_tag_values.s: test/test_tag_values.cc.s

.PHONY : test/test_tag_values.s

# target to generate assembly for a file
test/test_tag_values.cc.s:
	$(MAKE) -f CMakeFiles/all_the_tags_testrunner.dir/build.make CMakeFiles/all_the_tags_testrunner.dir/test/test_tag_values.cc.s
.PHONY : test/test_tag_values.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... all_the_tags_testrunner"
	@echo "... install"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... all_the_tags"
	@echo "... asmjit"
	@echo "... hayai_main"
	@echo "... sample"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... tests"
	@echo "... context.o"
	@echo "... context.i"
	@echo "... context.s"
	@echo "... query.o"
	@echo "... query.i"
	@echo "... query.s"
	@echo "... tag.o"
	@echo "... tag.i"
	@echo "... tag.s"
	@echo "... test/bench_query.o"
	@echo "... test/bench_query.i"
	@echo "... test/bench_query.s"
	@echo "... test/runner.o"
	@echo "... test/runner.i"
	@echo "... test/runner.s"
	@echo "... test/test_entitity_tagging.o"
	@echo "... test/test_entitity_tagging.i"
	@echo "... test/test_entitity_tagging.s"
	@echo "... test/test_helper.o"
	@echo "... test/test_helper.i"
	@echo "... test/test_helper.s"
	@echo "... test/test_query.o"
	@echo "... test/test_query.i"
	@echo "... test/test_query.s"
	@echo "... test/test_tag_implication.o"
	@echo "... test/test_tag_implication.i"
	@echo "... test/test_tag_implication.s"
	@echo "... test/test_tag_values.o"
	@echo "... test/test_tag_values.i"
	@echo "... test/test_tag_values.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

